using UnityEngine;
using UnityEngine.InputSystem;

public class SphereMovement : MonoBehaviour
{
    public float speed = 5f;
    private Rigidbody rigidBody;
    public PlayerControls controls; // Replace this with the name of the class generated by your Input Action Asset
    private void Awake() {
        rigidBody = GetComponent<Rigidbody>();
        
        // Assuming "PlayerControls" is the name of the generated class
        controls = new PlayerControls();

        // Enable the Move action
        controls.Gameplay.Move.performed += context => Move(context.ReadValue<Vector2>());
        controls.Gameplay.Move.canceled += _ => Move(Vector2.zero);
    }

    private void Move(Vector2 direction) {
        // Convert the 2D direction to a 3D vector to move on the XZ plane
        Vector3 moveDirection = new Vector3(direction.x, 0f, direction.y) * speed;
        
        // Apply the movement force to the sphere's Rigidbody
        rigidBody.AddForce(moveDirection);
    }

    private void OnEnable() {
        controls.Enable();
    }

    private void OnDisable() {
        controls.Disable();
    }

    void OnCollisionEnter(Collision collision)
    {
        if(collision.gameObject.tag == "LastRectangle"){
            Destroy(collision.gameObject);
            Destroy(gameObject);
            GameObject[] goArray = GameObject.FindGameObjectsWithTag("FinishText");
            Debug.Log("Array " + goArray.Length);
            if (goArray.Length > 0)
            {
                foreach (GameObject go in goArray)
                    {
                        Debug.Log("Text " + go.gameObject);
                        go.SetActive(true);
                    }
            }
        }
        Debug.Log("Collision " + collision.gameObject.tag);
    }
}
